"""Baselines: masked-diffusion, AR-LM, external-model adapters.

External-model protocol metadata is dependency-free and imported eagerly. Torch
baselines are resolved lazily through ``__getattr__`` so documentation and SOTA
registry tools still work in lightweight environments without PyTorch.
"""
from __future__ import annotations

from importlib import import_module

from .external_models import (
    ExternalModelSpec,
    ExternalResult,
    available_external_models,
    get_external_result,
    list_external_results,
)

_LAZY_EXPORTS = {
    "ARLMConfig": (".ar_lm", "ARLMConfig"),
    "ARLMTrainResult": (".ar_lm", "ARLMTrainResult"),
    "AutoregressiveLM": (".ar_lm", "AutoregressiveLM"),
    "ar_lm_loss": (".ar_lm", "ar_lm_loss"),
    "make_ar_lm_batch": (".ar_lm", "make_ar_lm_batch"),
    "sample_ar_lm": (".ar_lm", "sample_ar_lm"),
    "train_ar_lm": (".ar_lm", "train_ar_lm"),
    "DIFFUSION_INPUT_VOCAB_SIZE": (".masked_diffusion", "DIFFUSION_INPUT_VOCAB_SIZE"),
    "MASK_TOKEN": (".masked_diffusion", "MASK_TOKEN"),
    "MaskedDiffusionBaseline": (".masked_diffusion", "MaskedDiffusionBaseline"),
    "MaskedDiffusionConfig": (".masked_diffusion", "MaskedDiffusionConfig"),
    "MaskedDiffusionTrainResult": (".masked_diffusion", "MaskedDiffusionTrainResult"),
    "corrupt_with_masks": (".masked_diffusion", "corrupt_with_masks"),
    "make_fixed_canvas_batch": (".masked_diffusion", "make_fixed_canvas_batch"),
    "masked_diffusion_loss": (".masked_diffusion", "masked_diffusion_loss"),
    "sample_masked_diffusion": (".masked_diffusion", "sample_masked_diffusion"),
    "train_masked_diffusion": (".masked_diffusion", "train_masked_diffusion"),
    "FEATURE_NAMES": (".mrnabench_probe", "FEATURE_NAMES"),
    "MRNABenchLinearProbe": (".mrnabench_probe", "MRNABenchLinearProbe"),
    "MRNABenchProbeConfig": (".mrnabench_probe", "MRNABenchProbeConfig"),
    "MRNABenchProbeResult": (".mrnabench_probe", "MRNABenchProbeResult"),
    "count_trainable_params": (".mrnabench_probe", "count_trainable_params"),
    "feature_matrix": (".mrnabench_probe", "feature_matrix"),
    "record_feature_vector": (".mrnabench_probe", "record_feature_vector"),
    "run_mrnabench_probe": (".mrnabench_probe", "run_mrnabench_probe"),
    "synthetic_mrnabench_labels": (".mrnabench_probe", "synthetic_mrnabench_labels"),
    "CodonLatticeDPConfig": (".codon_lattice_dp", "CodonLatticeDPConfig"),
    "CodonLatticeDPResult": (".codon_lattice_dp", "CodonLatticeDPResult"),
    "boundary_stability_score": (".codon_lattice_dp", "boundary_stability_score"),
    "optimize_cds_synonymous": (".codon_lattice_dp", "optimize_cds_synonymous"),
    "optimize_record_cds": (".codon_lattice_dp", "optimize_record_cds"),
    "optimize_records_cds": (".codon_lattice_dp", "optimize_records_cds"),
    "run_codon_lattice_dp": (".codon_lattice_dp", "run_codon_lattice_dp"),
    "summarize_codon_lattice_results": (".codon_lattice_dp", "summarize_results"),
    "UTRLocalSearchConfig": (".utr_local_search", "UTRLocalSearchConfig"),
    "UTRLocalSearchResult": (".utr_local_search", "UTRLocalSearchResult"),
    "optimize_record_five_utr": (".utr_local_search", "optimize_record_five_utr"),
    "optimize_records_five_utr": (".utr_local_search", "optimize_records_five_utr"),
    "run_utr_local_search": (".utr_local_search", "run_utr_local_search"),
    "summarize_utr_local_search_results": (".utr_local_search", "summarize_results"),
    "UTRTeacherRow": (".utr_teacher_export", "UTRTeacherRow"),
    "export_utr_teacher_jsonl": (".utr_teacher_export", "export_utr_teacher_jsonl"),
    "score_record_utr_teacher_rows": (".utr_teacher_export", "score_record_utr_teacher_rows"),
    "summarize_utr_teacher_rows": (".utr_teacher_export", "summarize_teacher_rows"),
    "OBJECTIVE_LABELS": (".multiobjective_teacher_export", "OBJECTIVE_LABELS"),
    "DEFAULT_OBJECTIVE_WEIGHTS": (".multiobjective_teacher_export", "DEFAULT_OBJECTIVE_WEIGHTS"),
    "MultiObjectiveConfig": (".multiobjective_teacher_export", "MultiObjectiveConfig"),
    "MultiObjectiveTeacherRow": (".multiobjective_teacher_export", "MultiObjectiveTeacherRow"),
    "score_record_multiobjective_rows": (".multiobjective_teacher_export", "score_record_multiobjective_rows"),
    "summarize_multiobjective_rows": (".multiobjective_teacher_export", "summarize_multiobjective_rows"),
    "export_multiobjective_teacher_jsonl": (".multiobjective_teacher_export", "export_multiobjective_teacher_jsonl"),
    "ProteinConditionedCDSResult": (".protein_conditioned_cds", "ProteinConditionedCDSResult"),
    "seed_cds_from_protein": (".protein_conditioned_cds", "seed_cds_from_protein"),
    "design_cds_for_protein": (".protein_conditioned_cds", "design_cds_for_protein"),
    "design_records_for_proteins": (".protein_conditioned_cds", "design_records_for_proteins"),
    "summarize_protein_conditioned_designs": (".protein_conditioned_cds", "summarize_designs"),
    "run_protein_conditioned_design": (".protein_conditioned_cds", "run_protein_conditioned_design"),
    "run_protein_conditioned_gc_sweep": (".protein_conditioned_cds", "run_protein_conditioned_gc_sweep"),
    "HybridTeacherRow": (".hybrid_teacher_export", "HybridTeacherRow"),
    "export_hybrid_teacher_jsonl": (".hybrid_teacher_export", "export_hybrid_teacher_jsonl"),
    "CascadeTranscriptSignal": (".cascade_hard_negative_teacher", "CascadeTranscriptSignal"),
    "mine_cascade_hard_negative_teacher": (".cascade_hard_negative_teacher", "mine_cascade_hard_negative_teacher"),
    "write_hard_negative_teacher_markdown": (".cascade_hard_negative_teacher", "write_hard_negative_teacher_markdown"),
    "ExternalSOTADryRunRow": (".external_sota_dry_run", "ExternalSOTADryRunRow"),
    "dry_run_external_sota": (".external_sota_dry_run", "dry_run_external_sota"),
    "write_external_sota_artifacts": (".external_sota_dry_run", "write_external_sota_artifacts"),
    "write_external_sota_table": (".external_sota_dry_run", "write_external_sota_table"),
}


def __getattr__(name: str):
    """Resolve heavy baseline symbols only when accessed.

    Complexity is ``O(1)`` dictionary lookup plus the target module import cost.
    """
    if name not in _LAZY_EXPORTS:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module_name, attr_name = _LAZY_EXPORTS[name]
    module = import_module(module_name, __name__)
    value = getattr(module, attr_name)
    globals()[name] = value
    return value

__all__ = [
    "ARLMConfig",
    "ARLMTrainResult",
    "AutoregressiveLM",
    "ar_lm_loss",
    "make_ar_lm_batch",
    "sample_ar_lm",
    "train_ar_lm",
    "ExternalModelSpec",
    "ExternalResult",
    "available_external_models",
    "get_external_result",
    "list_external_results",
    "DIFFUSION_INPUT_VOCAB_SIZE",
    "MASK_TOKEN",
    "MaskedDiffusionBaseline",
    "MaskedDiffusionConfig",
    "MaskedDiffusionTrainResult",
    "corrupt_with_masks",
    "make_fixed_canvas_batch",
    "masked_diffusion_loss",
    "sample_masked_diffusion",
    "train_masked_diffusion",
    "FEATURE_NAMES",
    "MRNABenchLinearProbe",
    "MRNABenchProbeConfig",
    "MRNABenchProbeResult",
    "count_trainable_params",
    "feature_matrix",
    "record_feature_vector",
    "run_mrnabench_probe",
    "synthetic_mrnabench_labels",
    "CodonLatticeDPConfig",
    "CodonLatticeDPResult",
    "boundary_stability_score",
    "optimize_cds_synonymous",
    "optimize_record_cds",
    "optimize_records_cds",
    "run_codon_lattice_dp",
    "summarize_codon_lattice_results",
    "UTRLocalSearchConfig",
    "UTRLocalSearchResult",
    "optimize_record_five_utr",
    "optimize_records_five_utr",
    "run_utr_local_search",
    "summarize_utr_local_search_results",
    "UTRTeacherRow",
    "export_utr_teacher_jsonl",
    "score_record_utr_teacher_rows",
    "summarize_utr_teacher_rows",
    "OBJECTIVE_LABELS",
    "DEFAULT_OBJECTIVE_WEIGHTS",
    "MultiObjectiveConfig",
    "MultiObjectiveTeacherRow",
    "score_record_multiobjective_rows",
    "summarize_multiobjective_rows",
    "export_multiobjective_teacher_jsonl",
    "ProteinConditionedCDSResult",
    "seed_cds_from_protein",
    "design_cds_for_protein",
    "design_records_for_proteins",
    "summarize_protein_conditioned_designs",
    "run_protein_conditioned_design",
    "run_protein_conditioned_gc_sweep",
    "HybridTeacherRow",
    "export_hybrid_teacher_jsonl",
    "CascadeTranscriptSignal",
    "mine_cascade_hard_negative_teacher",
    "write_hard_negative_teacher_markdown",
    "ExternalSOTADryRunRow",
    "dry_run_external_sota",
    "write_external_sota_artifacts",
    "write_external_sota_table",
]
